name: AutoLayout

options:
  bundleIdPrefix: es.com.jano.autolayout
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.4

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:

  AutoLayout:
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - AutoLayoutTests
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.4
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.autolayout
       PRODUCT_NAME: AutoLayout
    sources: 
       - sources/main
    type: framework

  AutoLayoutTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 15.4
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.autolayout.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: AutoLayout
